### ISSUE TITLE
Unify `{% YouTube %}` shortcode for both web.dev and d.c.c

### ISSUE THREAD

**Issue by matthiasrohmer** [GoogleChrome/webdev-infra#50]
web.dev allows both an unnamed and and a named argument for the id (using the shortcode from this repo) while d.c.c allows specifiying a `startTime` via its own implementation. We should keep the (authoring) simplicity from web.dev while allowing `startTime` for both sites.

**Comment by simgobb** [comment]
At the moment DCC and Web.dev use different implementations for video embed. DCC uses an iFrame embed with lazy loading and web.dev uses a lite-youtube. In order to understand which implementation guarantees better performance I've run some tests.

_Test Scenario_: Comparing the performance of a standard YouTube iframe embed vs an embed using lite-youtube

_Test Environment_: Lighthouse mobile and desktop

_Test Cases_:

- Sample page with a single video
- Sample page with 10 videos

_Results_:

**_Test Case 1 - Sample page with a single video (desktop):_**

iFrame: FCP 0.4s, TTI 0.4s, LCP 0.5s, SpeedIndex 0.5s
lite-youtube: FCP 0.4s, TTI 0.4s, LCP 0.5s, SpeedIndex 0.5s

**_Test Case 2 - Sample page with a single video (mobile):_**

iFrame: FCP 1.6s, TTI 1.8s, LCP 2.5s, SpeedIndex 1.8s
lite-youtube: FCP 1.4s, TTI 2.4s, LCP 2.1s, SpeedIndex 1.5s

**_Test Case 3 - Sample page with 10 videos (desktop):_**

iFrame: FCP 0.4s, TTI 2.1s, LCP 0.6s, SpeedIndex 1.2s
lite-youtube: FCP 0.4s, TTI 0.4s, LCP 0.8s, SpeedIndex 0.5s

**_Test Case 4 -Sample page with 10 videos (mobile):_**

iFrame: FCP 1.5s, TTI 1.5s, LCP 2.1s, SpeedIndex 1.5s
lite-youtube: FCP 1.5s, TTI 2.5s, LCP 2.1s, SpeedIndex 1.6s

@matthiasrohmer @devnook

**Comment by tunetheweb** [comment]
So there’s a few things to consider here:

An iframe with lazy loading is only useful if the video is far enough down the page. If it’s in (or close to) the viewport then it’s not going to be lazy loaded. Would be good to know in above if any of the iframe videos were actually lazy loaded?

The youtube-lite actually delays the load of the video and replaces it with a big still image that acts like a button and loads the video only when clicked.

TTI is a very messy and (IMHO) unreliable metric. It’s more like “time until things settle a bit”. I’m also not sure how it deals with iframes to be honest. Anyway we’ve dropped TTI in Lighthouse 10 and are concentrating on TBT instead.

Over all I’m surprised there’s so little difference (and inconsistent difference to be honest).

Personally I’d vote for keeping the embed for a few reasons:
1. It’s more likely to guarantee good performance, rather than it be luck as to whether it’s on-screen or off screen.
2. It practices what we preach as we recommend the [facade pattern](https://developer.chrome.com/docs/lighthouse/performance/third-party-facades/) in [multiple places](https://web.dev/embed-best-practices/#replace-embeds-with-facades).
3. YouTube have [done some performance work](https://web.dev/better-youtube-web-part1/) but mostly to their own site rather than the embeds so far. We’ve been discussing with them some performance improvements for the embeds but it’s still work in progress. Once that’s done we could maybe revisit but, until then, I’d imagine the lite component is faster.
